package lv.lu.newsfeed.model.jpa.activity;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Transient;

import lv.lu.newsfeed.model.jpa.PersistentEntity;
import lv.lu.newsfeed.model.jpa.User;

/**
 * Base class for user activities (business objects stored in SQL database)
 * 
 * TODO [task]: add JPA annotations to make this hierarchy persistent.
 */
public abstract class Activity implements PersistentEntity {

    @Transient
    private static final SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd.MM.yyyy HH:mm:ss");
    
    private Long id;
    
    /* Date, when activity was generated by the user */
    private Date created;

    /* Reference to activity author (user created this activity) */
    private User author;

    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    public User getAuthor() {
        return author;
    }

    public Long getId() {
        return id;
    }

    public void setAuthor(User author) {
        this.author = author;
    }
    
    public String getFormattedDate(){
        return DATE_FORMAT.format(created);
    }
}
